### ISSUE TITLE
Known Issues: closeAction is not supported on Web at this point in time

### ISSUE THREAD

**Issue by startupgurukul** [papercups-io/papercups_flutter#50]
Hello folks, seems like the issue has been resolved using https://pub.dev/packages/pointer_interceptor

source:
https://github.com/flutter/flutter/issues/54027#issuecomment-747132587

**Comment by aguilaair** [comment]
Hey!

Thank you very much for the fix to this issue! If you have a moment I'd love to merge a PR. However, I'm not going to work on this issue right now because I'm releasing the new, fully dart coded plugin today/tomorrow, which will already fix this known issue. 

If you want to check out the 2.0 version check out the next branch on this repo! 

Kind regards,
Eduardo.

**Comment by startupgurukul** [comment]
Wow, that's great to hear..Looking forward Edurado.

**Comment by startupgurukul** [comment]
It would be interesting if the dart version can be used on web as well thanks to flutter support for web

**Comment by aguilaair** [comment]
It is supported, see the demo at papercups-demo.eduardom.dev
